### ISSUE TITLE
xApp Python script needs to be started before the connector sh script

### ISSUE THREAD

**Issue by leonardobonati** [wineslab/OAI-colosseum-ric-integration#1]
The Python script for the base xApp needs to start before the connector sh script since the Python script is waiting for incoming connections. Otherwise the connector will give an error while trying to connect to since the Python portion is not running yet.

This:
```
docker exec -it base-xapp-24 bash
cd ../xapp-oai/base-xapp/
python3 run_xapp.py
```

needs to be started before this:
```
docker exec -it base-xapp-24 bash
cd ../xapp-oai/xapp-sm-connector/
./run_xapp.sh
```

**Comment by EugenioMoro** [comment]
Xapp-sm-connector encodes a list of periodically updated ran parameters in the subscription request. This list is not generated in the connector, but it comes as a protobuf payload from the python xapp. For this reason, at the moment, this modified xapp-sm-connector needs to start before the python xapp. Once ready, it will wait for the buffer from the python xapp and then send out sub requests

**Comment by leonardobonati** [comment]
Uhm, weird. This is not what happened in the tests Jonah and I did yesterday with the "local" gNB. The connector started and gave error in connecting with the Python script and skipped ahead.

**Comment by EugenioMoro** [comment]
Yes that is weird. What's happening is that the xapp-sm-connector you are running is the vanilla version. That's probably because the docker image is building from the wrong source, due to some settings not saved after a failed colosseum snapshot. I promise to look into this and fix it asap. In the meantime, a workaround would be pulling this working xapp docker image from dockerhub: emoro/oran-images:xapp and use it in place of the local built image

**Comment by leonardobonati** [comment]
Ok thanks.

**Comment by EugenioMoro** [comment]
Fixed!
